### ISSUE TITLE
Change Whitelist to those with Zeus Role

### ISSUE THREAD

**Issue by arma3goddess** [Ben-Hinton/arma-3-server-scripts#2]
change the whitelist of avaliable users from those with the staff permissions to those with the zeus permissions to allow zeuses to upload their own missions without the input of staff

**Comment by Ben-Hinton** [comment]
Great suggestion @arma3goddess, I will implement this shortly

**Comment by Ben-Hinton** [comment]
@arma3goddess I have now implemented the feature, thanks for the suggestion 👍
